# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moya-laboratory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moya-laboratory
	pod 'Then'
	pod 'Moya'
	pod 'SwiftLint'
	pod 'Kingfisher', '~> 7.0'
end
